
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo-api?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show_sql: true
    hibernate:
      ddl-auto: create-drop
